name: APOC-commandsync
version: @version@
main: org.apocgaming.apocsync.bukkit.Main
description: sends admin commands to servers on the network for apocgaming.org
commands:
  apocexec:
    aliases: [ae]
    description: Admin commands.