name: APOC-CommandSync
main: org.apocgaming.apocsync.bukkit.Main
version: 1.0
author: braddevans
description: something made for apocgaming.org

commands:
   apocexec:
     description: executes command on all servers
     aliases: [ae, apocexec]
     permission: apocexec.admin
     usage: /apocexec <command [args]>

permissions:
 apocexec.*:
   description: Gives access to all apoc global executor commands.
   children:
     apocexec.admin: true
 apocexec.admin:
   description: execute commands globaly
   default: op